name: ReplayAPI
main: de.sebpas.replay.ReplaySystem
version: 1.0
authors: [SPMinecraftWorld, thepn,]
commands:
  rplstart:
    usage: /start
    description: starts the replay recorder
  rplstop:
    usage: /stop
    description: stops the replay recorder
  replay:
permissions:
  replay.*:
    description: Erlaubt Zugriff auf alle Befehle des Replay - Plugins.
    children:
      replay.command: true
  replay.command:
    default: op